---@meta
-- Generated by PZEventDoc https://github.com/demiurgeQuantified/PZEventDoc

-- If it helped you, please consider leaving me a tip ^u^
-- https://ko-fi.com/starseamstress

Events = {}

---(Deprecated) 
---@deprecated
Events.OnAIStateEnter = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnAIStateExecute = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnAIStateExit = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnAddBuilding = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnBeingHitByZombie = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnChangeWeather = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnCharacterCreateStats = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnCharacterMeet = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnDawn = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnDoTileBuilding = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnDusk = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnIsoThumpableLoad = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnIsoThumpableSave = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnLoginState = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnLoginStateSuccess = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnMakeItem = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnMapLoadCreateIsoObject = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnNewSurvivorGroup = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnNPCSurvivorUpdate = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnPlayerSetSafehouse = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnPostCharactersSquareDraw = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnPostFloorSquareDraw = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnPostTileDraw = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnPostTilesSquareDraw = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnPostWallSquareDraw = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnPreGameStart = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnRadioInteraction = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnRainStart = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnRainStop = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnRenderUpdate = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnVehicleHorn = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Events.OnWorldMessage = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}

Hook = {}

---(Deprecated) 
---@deprecated
Hook.UseItem = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
---(Deprecated) 
---@deprecated
Hook.WeaponSwingHitPoint = {
    ---@param func function
    Add = function(func) end,
    ---@param func function
    Remove = function(func) end,
}
